version: '3.8'

services:
  postgres:
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 297032
      POSTGRES_DB: oauth2
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d oauth2"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  oauth25:
    image: oauth25:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/oauth2
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 297032
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge